version: '3.8'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - alikri_bridge_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: Iamuser
      POSTGRES_PASSWORD: Iampassword
      POSTGRES_DB: Iamdatabase
    networks:
      - alikri_bridge_network

networks:
  alikri_bridge_network:
    driver: bridge
