version: '3.8'
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:4000" 
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
      - node_modules:/app/node_modules 
    depends_on:
      - db
    networks:
      - alikri_bridge_network
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - alikri_bridge_network
    restart: always 

volumes:
  db_data:
    driver: local
  db_logs:  
    driver: local

networks:
  alikri_bridge_network:
    driver: bridge
